@auth_url={{api_url}}/auth

POST {{auth_url}}/signin
content-type: application/json

{
    "username": "username1",
    "password": "password1"
}
###

POST {{auth_url}}/signout
###

POST {{auth_url}}/register
content-type: application/json

{
    "email": "email1@test.com",
    "username": "username1",
    "password": "password"
}
###

GET {{auth_url}}/me
###

POST {{auth_url}}/refresh
###