POST {{api_url}}/users
content-type: application/json

{
    "email": "email4@test.com",
    "username": "user4"
}
###

PUT {{api_url}}/users/f59bde4d-1925-46a5-8f8c-bf3efa692366
content-type: application/json

{
    "email": "",
    "username": "user2"
}
###

DELETE {{api_url}}/users/73deb29a-0ea3-49f7-ab4b-36363f138954
###

GET {{api_url}}/users
###

GET {{api_url}}/users?order_dir=asc
###

GET {{api_url}}/users
###

GET {{api_url}}/users/53091e0d-c0c1-4c37-b103-28248e7a69cb
###