name: Deploy

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        name: Build image
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and export
              uses: docker/build-push-action@v5
              with:
                  context: .
                  outputs: type=docker,dest=/tmp/tdoo-backend.tar

            - name: Upload image
              uses: actions/upload-artifact@v4
              with:
                  name: tdoo-backend
                  path: /tmp/tdoo-backend.tar

    deploy:
        name: Deploy server
        runs-on: ubuntu-22.04
        needs: build
        steps:
            - name: Setup SSH
              run: |
                  mkdir -p ~/.ssh/
                  echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
                  chmod 600 ~/.ssh/id_ed25519
                  ssh-keyscan -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts
                  cat >>~/.ssh/config <<END
                  Host deploy
                    HostName ${{ secrets.SSH_HOST }}
                    User ${{ secrets.SSH_USER }}
                    IdentityFile ~/.ssh/id_ed25519
                  END

            - name: Download image
              uses: actions/download-artifact@v4
              with:
                  name: tdoo-backend
                  path: /tmp

            - name: Upload image to server
              run: scp /tmp/tdoo-backend.tar ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/app
