name: Deploy

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    deploy:
        name: 'Deploy'
        runs-on: ubuntu-latest
        env:
            TARGET_DIR: ~/tdoo-backend
            REPO_URL: git@github.com-tdoo-backend:mrheio/tdoo-backend.git

        steps:
            - name: Configure SSH
              env:
                  SSH_HOST: ${{ secrets.SSH_HOST }}
                  SSH_USER: ${{ secrets.SSH_USERNAME }}
                  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
              run: |
                  mkdir -p ~/.ssh/
                  echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy
                  chmod 600 ~/.ssh/deploy
                  cat >>~/.ssh/config <<END
                  Host deploy
                    HostName $SSH_HOST
                    User $SSH_USER
                    IdentityFile ~/.ssh/deploy
                    StrictHostKeyChecking no
                  END

            - name: Pull/Clone app repo
              run: ssh deploy 'cd ~ && git -C ${{ env.TARGET_DIR }} pull || git clone ${{ env.REPO_URL }} ${{ env.TARGET_DIR }}'

            - name: Install packages
              run: ssh deploy 'cd ${{ env.TARGET_DIR }} && npm i'

            - name: Build app
              run: ssh deploy 'cd ${{ env.TARGET_DIR }} && npm run build'

            - name: Copy env variables
              run: ssh deploy 'cd ${{ env.TARGET_DIR }} &&
                  rm -rf .env &&
                  echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env &&
                  echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env'

            - name: (re)Start app
              run: ssh deploy 'cd ${{ env.TARGET_DIR }} &&
                  pm2 restart dist/index.js --name tdoo-backend --update-env'
